#pragma once

#ifndef LOGGER_H
#define LOGGER_H

#include "ILogger.h"
#include "LoggerMultiton.h"
#include "LogEntry.h"

#include <memory>
#include <string>

/*
* Log messages generated by the code
*/
class Logger : public ILogger
{
public:
	// TODO Destructor is public because of shared pointer. Investigate make_shared?
	~Logger();

	void log(const std::string& logLevel, const std::string& message);
	friend std::ostream& operator<<(std::ostream& os, const Logger& logger);

private:
	Logger();
	friend std::shared_ptr<ILogger> LoggerMultiton::getLogger(std::string key);

	std::vector<LogEntry> m_messages;
};

#endif
